# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
#   namespace: event-example
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv
#   namespace: event-example
# spec:
#   capacity:
#     storage: 50Mb
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: /tmp
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - pull-build.event-example.example.com
#           - app-runner.event-example.example.com
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: local-pv-claim
#   namespace: event-example
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 25Mb
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: build-pv
  namespace: argo-test
  labels:
    type: local
spec:
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    #volume is at /mnt/data on the cluster's Node
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pv-claim
  namespace: argo-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250M