apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: entry-route
  namespace: argo-test
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
  - knative-ingress-gateway.knative-serving.svc.cluster.local
  # Set host to the domain name that you own.
  hosts:
  - example.com
  http:
  - match:
    - uri:
        prefix: "/payload"
    rewrite:
      # Rewrite the GitHub payload URL in order to redirect requests to Webhook service.
      authority: webhook.argo-test.example.com
    route:
      # istio-ingressgateway is the k8s service created by Knative as the shared gateway of all traffic incoming to the cluster.
      # Basically we redirect the request to the cluster entry so the request will be directed to Webhook service.
      - destination:
          host: istio-ingressgateway.istio-system.svc.cluster.local
          port:
            number: 80
        weight: 100