apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: pull-build-test
  generateName: pull-build-test-   # name of the workflow spec
  namespace: argo-test
spec:
  entrypoint: pull-build-test
  templates:
  - name: pull-build-test
    steps:
    - - name: integration-test-deployment
        template: integration-test-deployment
      - name: integration-test-service
        template: integration-test-service
      - name: pull-build
        template: pull-build
        # arguments:
        #   parameters: 
        #   - name: ip
        #     value: "{{steps.pull-build.name}}"

  - name: integration-test-deployment
    # inputs:
    #   parameters:
    #     - name: ip
    resource:
      action: apply
      manifest: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: integration-test
          namespace: argo-test
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{workflow.name}}"
            uid: "{{workflow.uid}}"
        spec:
          selector:
            matchLabels: &labels
              app: integration-test
          template:
            metadata:
              labels: *labels
            spec:
              containers:
                - image: myregistry.com/integration-test@sha256:eeabf1949f68ff08c9306689c9032543db663a9898170932f0153a3459a21986
                  name: integration-test
                  imagePullPolicy: IfNotPresent
                  resources:                # limit the resources
                    limits:
                      memory: 1024Mi
                      cpu: 200m
                  env:
                    - name: POD_NAMESPACE
                      valueFrom: 
                        fieldRef: 
                          fieldPath: metadata.namespace
                    - name: WORKFLOW_NAME
                      value: "{{workflow.name}}"
                      # valueFrom: 
                      #   fieldRef: 
                      #     fieldPath: metadata.name
                  # ports:
                  # - containerPort: 8080
              imagePullSecrets:
                - name: regcred

  - name: pull-build
    #daemon: true # crash after launch
    container:
      image: myregistry.com/pull-build@sha256:e1e6d32e421fe34b23bcdd4d8a1c69b18d8dd60da95bb369be88bf015dacafe1
      resources:                # limit the resources
        limits:
          memory: 512Mi
          cpu: 400m
      env:
        - name: GIT_USER
          value: sltang
        - name: GIT_REPO
          value: jenkins-x-test
        - name: POD_IP
          valueFrom: 
            fieldRef: 
              fieldPath: status.podIP
      imagePullSecrets:
        - name: regcred

  - name: integration-test-service
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: integration-test
          namespace: argo-test
          ownerReferences:
          - apiVersion: argoproj.io/v1alpha1
            blockOwnerDeletion: true
            kind: Workflow
            name: "{{workflow.name}}"
            uid: "{{workflow.uid}}"
        spec:
          selector:
            app: integration-test
          ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
  
  
  