apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: webhook
  namespace: argo-test
spec:
  template:
    spec:
      containers:
      - image: myregistry.com/webhook@sha256:f03788d8e5d5aed5e8fc737726b120955516b70397aa6dd7f9afddba9d99f8ef
        ports:
        - containerPort: 4567
        readinessProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 1
        env:
          - name: POD_NAMESPACE
            value: argo-test
          - name: WORKFLOW_NAME
            value: pull-build-test
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: github-webhook-secret
                key: secret